### ISSUE TITLE
Não mostra a mensagem da ArithmeticException

### ISSUE THREAD

**Issue by kayladeodato** [cami-la/exceptions-java#16]
Olá @cami-la ! Espero que esteja bem! :)
Primeiramente gostaria de parabenizar pela sua didática e pelos exemplos que trazes nas aulas, me ajudam bastante a entender os conceitos.

Gostaria de sua ajuda para entender porque não mostra a janela com a mensagem no cath em que não é possível dividir por zero. A Exception de NumberException mostra a mensagem normalmente. Segue o código abaixo, caso precise dar uma olhada:

`public class UncheckedException {
    public static void main(String[] args) {

        boolean continueLooping = true;
        double resultado = 0.0;

        do {

            try {
                String a = JOptionPane.showInputDialog(("Numerador: "));
                String b = JOptionPane.showInputDialog("Denominador: ");
                resultado = dividir(Double.parseDouble(a), Double.parseDouble(b));
                System.out.println(a + " / " + b + " = " + resultado);
                continueLooping = false;

            } catch (NumberFormatException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Entrada inválida, informe um número.");

            } catch (ArithmeticException e ) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Impossível dividir um número por zero.");

            } finally {
                System.out.println("Fim do programa");
            }
        } while (continueLooping);

    }

    public static double dividir (double a, double b) {
        return (a / b);
    }`

Agradeço desde já! 👍🏼

**Comment by cami-la** [comment]
Oi, @kayladeodato. Tudo certinho? (:
Primeiramente muito obrigada pelo feedback. Fico muito feliz que esteja gostando dos conteúdos, e o melhor, vou regrava-los. 

Então, na verdade quando você utiliza a entradas do tipo `double` e faz a divisão, mesmo que o denominador seja 0, nunca irá lançar uma `ArithemeticExcepiton`, pois o resultado sempre será `infinity`.
**Para lançar uma  `ArithemeticExcepiton` precisa ser uma divisão de 2 números inteiros.**

Segue o exemplo:

![byzero](https://user-images.githubusercontent.com/64323124/217797705-dbde2a57-9e49-4caf-8f26-614fb91b7031.png)

```java
import javax.swing.*;

public class Main {
  public static void main(String[] args) {
    boolean continueLooping = true;
    double resultado = 0.0;

    do {
      try {
        String a = JOptionPane.showInputDialog(("Numerador: "));
        String b = JOptionPane.showInputDialog("Denominador: ");
        //resultado = dividir(Double.parseDouble(a), Double.parseDouble(b));
        resultado = dividir(Integer.parseInt(a), Integer.parseInt(b));
        System.out.println(a + " / " + b + " = " + resultado);
        continueLooping = false;
      } catch (NumberFormatException e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Entrada inválida, informe um número.");

      } catch (ArithmeticException e ) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Impossível dividir um número por zero.");
      } finally {
        System.out.println("Fim do programa");
      }
    } while (continueLooping);
  }

  public static double dividir (double a, double b) {
    return (a / b);
  }

  public static double dividir (int a, int b) {
    return (a / b);
  }
}
```

Se ainda ficou alguma dúvida, fico à disposição!

**Comment by cami-la** [comment]
Ah, também recomendo sempre colocar uma `Exception` mais genérica. Porque o usuário ele sempre encontra formas interessantes para quebrar o nosso código. kkkkk
Do jeito que você está capturando as Exceptions, se acontecer alguma outra exception além da `Arithmetic` e `NumberFormat`, seu programa não consegue capturar.

![algo estranho](https://user-images.githubusercontent.com/64323124/217804728-41844d43-140a-4fdc-a17c-413eb9847c33.png)

_Importante lembrar que as exceptions mais genericas sempre são capturadas por último!_

**Comment by kayladeodato** [comment]
Obrigada pela ajuda e considerações, Camila! :) 
Ajudou bastante! ❤️
